/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.views.*;
import java.awt.Color;

/**
 *
 * @author USUARIO
 */
public class Compras extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Compras() {
        initComponents();

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comprasPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ingresoIdentificacion = new javax.swing.JLabel();
        ingresoIdentificacionTxt = new javax.swing.JTextField();
        ingresoIdPrenda = new javax.swing.JLabel();
        ingresoIdPrendaTxt = new javax.swing.JTextField();
        realizarCompra = new javax.swing.JButton();
        ingresoIdPrenda1 = new javax.swing.JLabel();
        ingresoIdPrendaTxt1 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(744, 419));

        comprasPanel.setBackground(new java.awt.Color(255, 255, 255));
        comprasPanel.setPreferredSize(new java.awt.Dimension(750, 440));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/istockphoto-1388108025-612x612.jpg"))); // NOI18N

        ingresoIdentificacion.setText("IDENTIFICACION DEL CLIENTE");

        ingresoIdentificacionTxt.setForeground(new java.awt.Color(204, 204, 204));
        ingresoIdentificacionTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        ingresoIdentificacionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoIdentificacionTxtActionPerformed(evt);
            }
        });

        ingresoIdPrenda.setText("ID PRENDA");

        ingresoIdPrendaTxt.setForeground(new java.awt.Color(204, 204, 204));
        ingresoIdPrendaTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        ingresoIdPrendaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoIdPrendaTxtActionPerformed(evt);
            }
        });

        realizarCompra.setBackground(new java.awt.Color(102, 102, 102));
        realizarCompra.setForeground(new java.awt.Color(255, 255, 255));
        realizarCompra.setText("Realizar Compra");
        realizarCompra.setBorderPainted(false);
        realizarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        realizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarCompraActionPerformed(evt);
            }
        });

        ingresoIdPrenda1.setText("CANTIDAD");

        ingresoIdPrendaTxt1.setForeground(new java.awt.Color(204, 204, 204));
        ingresoIdPrendaTxt1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        ingresoIdPrendaTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoIdPrendaTxt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout comprasPanelLayout = new javax.swing.GroupLayout(comprasPanel);
        comprasPanel.setLayout(comprasPanelLayout);
        comprasPanelLayout.setHorizontalGroup(
            comprasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comprasPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(comprasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingresoIdentificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addGroup(comprasPanelLayout.createSequentialGroup()
                        .addGroup(comprasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(comprasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ingresoIdentificacionTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                .addComponent(ingresoIdPrenda, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ingresoIdPrendaTxt, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(ingresoIdPrenda1)
                            .addComponent(ingresoIdPrendaTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comprasPanelLayout.createSequentialGroup()
                        .addComponent(realizarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)))
                .addContainerGap())
        );
        comprasPanelLayout.setVerticalGroup(
            comprasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comprasPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comprasPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(ingresoIdentificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingresoIdentificacionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ingresoIdPrenda, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingresoIdPrendaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ingresoIdPrenda1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingresoIdPrendaTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(realizarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comprasPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comprasPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ingresoIdentificacionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoIdentificacionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoIdentificacionTxtActionPerformed

    private void ingresoIdPrendaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoIdPrendaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoIdPrendaTxtActionPerformed

    private void realizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_realizarCompraActionPerformed

    private void ingresoIdPrendaTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoIdPrendaTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoIdPrendaTxt1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel comprasPanel;
    private javax.swing.JLabel ingresoIdPrenda;
    private javax.swing.JLabel ingresoIdPrenda1;
    private javax.swing.JTextField ingresoIdPrendaTxt;
    private javax.swing.JTextField ingresoIdPrendaTxt1;
    private javax.swing.JLabel ingresoIdentificacion;
    private javax.swing.JTextField ingresoIdentificacionTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton realizarCompra;
    // End of variables declaration//GEN-END:variables
}
