/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.interfaces.DAOUsuarios;
import com.mycompany.mavac_proyect.DAOUsuariosImpl;
import com.mycompany.views.*;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class nuevoUsuario extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public nuevoUsuario() {
        initComponents();
        initStyles();

    }
    boolean isEdition=false;
    private void limpiarCampos() {
        nombreTxt.setText("");
        apellidoPTxt.setText("");
        apellidoMTxt.setText("");
        identificacionTxt.setText("");
        residenciaTxt.setText("");
        direccionTxt.setText("");
        telefonoTxt.setText("");

        nombreTxt.requestFocus();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevoUsuarioPanel = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        apellidoPTxt = new javax.swing.JTextField();
        apellidoP = new javax.swing.JLabel();
        apellidoM = new javax.swing.JLabel();
        apellidoMTxt = new javax.swing.JTextField();
        identificacion = new javax.swing.JLabel();
        identificacionTxt = new javax.swing.JTextField();
        residencia = new javax.swing.JLabel();
        residenciaTxt = new javax.swing.JTextField();
        direccion = new javax.swing.JLabel();
        direccionTxt = new javax.swing.JTextField();
        telefono = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JTextField();
        btn_registrar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(744, 419));

        nuevoUsuarioPanel.setBackground(new java.awt.Color(255, 255, 255));

        Titulo.setText("Registrar Nuevo Cliente");

        nombre.setText("Nombre");

        nombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTxtActionPerformed(evt);
            }
        });

        apellidoPTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoPTxtActionPerformed(evt);
            }
        });

        apellidoP.setText("Apellido Paterno");

        apellidoM.setText("Apellido Materno");

        apellidoMTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoMTxtActionPerformed(evt);
            }
        });

        identificacion.setText("Identificacion");

        identificacionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificacionTxtActionPerformed(evt);
            }
        });

        residencia.setText("Residencia");

        direccion.setText("Direccion");

        telefono.setText("Telefono");

        btn_registrar.setBackground(new java.awt.Color(102, 102, 102));
        btn_registrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrar.setText("Registrar");
        btn_registrar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        btn_registrar.setBorderPainted(false);
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nuevoUsuarioPanelLayout = new javax.swing.GroupLayout(nuevoUsuarioPanel);
        nuevoUsuarioPanel.setLayout(nuevoUsuarioPanelLayout);
        nuevoUsuarioPanelLayout.setHorizontalGroup(
            nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                        .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addGap(204, 204, 204))
                    .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                        .addComponent(identificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                        .addGap(176, 176, 176))
                    .addComponent(identificacionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                        .addComponent(apellidoM, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addGap(156, 156, 156))
                    .addComponent(apellidoMTxt)
                    .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                        .addComponent(apellidoP, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                        .addGap(160, 160, 160))
                    .addComponent(apellidoPTxt)
                    .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                        .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(124, 124, 124))
                    .addComponent(nombreTxt))
                .addGroup(nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(btn_registrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(57, 57, 57))
                    .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(residencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(residenciaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(direccionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(telefonoTxt))
                        .addContainerGap())))
        );
        nuevoUsuarioPanelLayout.setVerticalGroup(
            nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(residencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(residenciaTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(direccionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(apellidoPTxt))
                .addGap(18, 18, 18)
                .addGroup(nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(apellidoMTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                    .addComponent(telefonoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(identificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(identificacionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                    .addComponent(btn_registrar, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addGap(89, 89, 89))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nuevoUsuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nuevoUsuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTxtActionPerformed

    private void apellidoPTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoPTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoPTxtActionPerformed

    private void apellidoMTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoMTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoMTxtActionPerformed

    private void identificacionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificacionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificacionTxtActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        String nombre = nombreTxt.getText().trim();
        String apellidoP = apellidoPTxt.getText().trim();
        String apellidoM = apellidoMTxt.getText().trim();
        String identificacionStr = identificacionTxt.getText().trim();
        String residencia = residenciaTxt.getText().trim();
        String direccion = direccionTxt.getText().trim();
        String telefono = telefonoTxt.getText().trim();


        if (nombre.isEmpty() || apellidoP.isEmpty() || apellidoM.isEmpty() || 
            identificacionStr.isEmpty() || residencia.isEmpty() || 
            direccion.isEmpty() || telefono.isEmpty()) {
    
            javax.swing.JOptionPane.showMessageDialog(this, 
            "Debe llenar todos los campos", 
            "AVISO", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    
            nombreTxt.requestFocus();
            return;
        }

        // Validar identificación como número
        int identificacion;
        try {
            identificacion = Integer.parseInt(identificacionStr);
    
            // Validaciones adicionales
            if (identificacion <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "La identificación debe ser un número positivo", 
                    "ERROR", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
                identificacionTxt.requestFocus();
                return;
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "La identificación debe ser un número válido", 
                "ERROR", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            identificacionTxt.requestFocus();
            return;
        }

// Validar longitud de campos
        if (nombre.length() < 2 || apellidoP.length() < 2 || apellidoM.length() < 2) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Nombres y apellidos deben tener al menos 2 caracteres", 
                "ERROR", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            nombreTxt.requestFocus();
            return;
        }

// Validar formato de teléfono (ejemplo: solo números y 10 dígitos)
        if (!telefono.matches("\\d{10}")) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "El teléfono debe tener 10 dígitos", 
                "ERROR", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            telefonoTxt.requestFocus();
            return;
        }

// Crear y registrar usuario
        com.mycompany.models.Usuarios usuario = new com.mycompany.models.Usuarios();
        usuario.setNombre(nombre);
        usuario.setApellido_p(apellidoP);
        usuario.setApellido_m(apellidoM);
        usuario.setIdentificacion(identificacion);
        usuario.setDireccion(direccion);
        usuario.setResidencia(residencia);
        usuario.setTelefono(telefono);

        try {
            DAOUsuarios dao = new DAOUsuariosImpl();
            dao.registrar(usuario);
    

            javax.swing.JOptionPane.showMessageDialog(this, 
                "Usuario registrado exitosamente", 
                "ÉXITO", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    

            limpiarCampos();
    
        } catch (Exception e) {

            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error al registrar usuario: " + e.getMessage(), 
                "ERROR", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
    

            System.err.println("Error de registro: " + e.getMessage());
        }


      
    }//GEN-LAST:event_btn_registrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel apellidoM;
    private javax.swing.JTextField apellidoMTxt;
    private javax.swing.JLabel apellidoP;
    private javax.swing.JTextField apellidoPTxt;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JLabel direccion;
    private javax.swing.JTextField direccionTxt;
    private javax.swing.JLabel identificacion;
    private javax.swing.JTextField identificacionTxt;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JPanel nuevoUsuarioPanel;
    private javax.swing.JLabel residencia;
    private javax.swing.JTextField residenciaTxt;
    private javax.swing.JLabel telefono;
    private javax.swing.JTextField telefonoTxt;
    // End of variables declaration//GEN-END:variables

    private void initStyles() {
        Titulo.putClientProperty("FlatLaf.styleClass", "h1");
        Titulo.setForeground(Color.black);
        nombreTxt.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del usuario.");
        apellidoPTxt.putClientProperty("JTextField.placeholderText", "Ingrese el apellido paterno del usuario.");
        apellidoMTxt.putClientProperty("JTextField.placeholderText", "Ingrese el apellido materno del usuario.");
        residenciaTxt.putClientProperty("JTextField.placeholderText", "Ingrese la residencia del usuario.");
        telefonoTxt.putClientProperty("JTextField.placeholderText", "Ingrese el teléfono del usuario.");
        identificacionTxt.putClientProperty("JTextField.placeholderText","Ingrese la identificacion del usuario");
        direccionTxt.putClientProperty("JTextField.placeholderText", "Ingrese la direccion del usuario");
      
        

        
    
    }

}
