/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.views.*;
import java.awt.Color;

/**
 *
 * @author USUARIO
 */
public class nuevoProducto extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public nuevoProducto() {
        initComponents();
        initStyles();

    }
    boolean isEdition=false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevoUsuarioPanel = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        apellidoPTxt = new javax.swing.JTextField();
        apellidoP = new javax.swing.JLabel();
        apellidoM = new javax.swing.JLabel();
        apellidoMTxt = new javax.swing.JTextField();
        identificacion = new javax.swing.JLabel();
        identificacionTxt = new javax.swing.JTextField();
        residencia = new javax.swing.JLabel();
        residenciaTxt = new javax.swing.JTextField();
        direccion = new javax.swing.JLabel();
        direccionTxt = new javax.swing.JTextField();
        telefono = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JTextField();
        btn_registrar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(744, 419));

        nuevoUsuarioPanel.setBackground(new java.awt.Color(255, 255, 255));

        Titulo.setText("Registrar Nuevo Producto");

        nombre.setText("Nombre ");

        nombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTxtActionPerformed(evt);
            }
        });

        apellidoPTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoPTxtActionPerformed(evt);
            }
        });

        apellidoP.setText("Cantidad");

        apellidoM.setText("Precio de venta");

        apellidoMTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoMTxtActionPerformed(evt);
            }
        });

        identificacion.setText("Precio de Costo");

        identificacionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificacionTxtActionPerformed(evt);
            }
        });

        residencia.setText("ID del producto");

        direccion.setText("Marca");

        telefono.setText("Descripcion del Producto");

        btn_registrar.setBackground(new java.awt.Color(153, 153, 153));
        btn_registrar.setText("Registrar");
        btn_registrar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        btn_registrar.setBorderPainted(false);

        javax.swing.GroupLayout nuevoUsuarioPanelLayout = new javax.swing.GroupLayout(nuevoUsuarioPanel);
        nuevoUsuarioPanel.setLayout(nuevoUsuarioPanelLayout);
        nuevoUsuarioPanelLayout.setHorizontalGroup(
            nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                        .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(204, 204, 204))
                    .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                        .addComponent(identificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(176, 176, 176))
                    .addComponent(identificacionTxt)
                    .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                        .addComponent(apellidoM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(156, 156, 156))
                    .addComponent(apellidoMTxt)
                    .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                        .addComponent(apellidoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(160, 160, 160))
                    .addComponent(apellidoPTxt)
                    .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                        .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(124, 124, 124))
                    .addComponent(nombreTxt))
                .addGroup(nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(residenciaTxt)
                            .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                                .addComponent(residencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(227, 227, 227))
                            .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                                .addComponent(direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(233, 233, 233))
                            .addComponent(direccionTxt)
                            .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                                .addComponent(telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(237, 237, 237))
                            .addComponent(telefonoTxt))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoUsuarioPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))))
        );
        nuevoUsuarioPanelLayout.setVerticalGroup(
            nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Titulo)
                .addGap(26, 26, 26)
                .addGroup(nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(residencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(residenciaTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                        .addComponent(apellidoP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellidoPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nuevoUsuarioPanelLayout.createSequentialGroup()
                        .addComponent(direccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(direccionTxt)))
                .addGap(18, 18, 18)
                .addGroup(nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoM)
                    .addComponent(telefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoMTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(identificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identificacionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nuevoUsuarioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nuevoUsuarioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTxtActionPerformed

    private void apellidoPTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoPTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoPTxtActionPerformed

    private void apellidoMTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoMTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoMTxtActionPerformed

    private void identificacionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificacionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificacionTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel apellidoM;
    private javax.swing.JTextField apellidoMTxt;
    private javax.swing.JLabel apellidoP;
    private javax.swing.JTextField apellidoPTxt;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JLabel direccion;
    private javax.swing.JTextField direccionTxt;
    private javax.swing.JLabel identificacion;
    private javax.swing.JTextField identificacionTxt;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JPanel nuevoUsuarioPanel;
    private javax.swing.JLabel residencia;
    private javax.swing.JTextField residenciaTxt;
    private javax.swing.JLabel telefono;
    private javax.swing.JTextField telefonoTxt;
    // End of variables declaration//GEN-END:variables

    private void initStyles() {
        Titulo.putClientProperty("FlatLaf.styleClass", "h1");
        Titulo.setForeground(Color.black);
        nombreTxt.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del usuario.");
        apellidoPTxt.putClientProperty("JTextField.placeholderText", "Ingrese el apellido paterno del usuario.");
        apellidoMTxt.putClientProperty("JTextField.placeholderText", "Ingrese el apellido materno del usuario.");
        residenciaTxt.putClientProperty("JTextField.placeholderText", "Ingrese la residencia del usuario.");
        telefonoTxt.putClientProperty("JTextField.placeholderText", "Ingrese el teléfono del usuario.");
      
        

        
    
    }
}
