/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.views.*;
import java.awt.Color;

/**
 *
 * @author USUARIO
 */
public class Principal extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        initStyles();
    }
    private void initStyles(){
        Titulo.putClientProperty("FlatLaf.style", "font: light $h1.regular.font");
        Titulo.setForeground(Color.black);
        nav1Txt.putClientProperty("FlatLaf.styleClass", "large");
        nav1Txt.setForeground(Color.black);
        nav2Txt.putClientProperty("FlatLaf.styleClass", "large");
        nav2Txt.setForeground(Color.black);
        toolTxt.putClientProperty("FlatLaf.styleClass", "large");
        toolTxt.setForeground(Color.black);
        inventarioTxt.putClientProperty("FlatLaf.styleClass", "large");
        inventarioTxt.setForeground(Color.black);
        ventasTxt.putClientProperty("FlatLaf.styleClass", "large");
        ventasTxt.setForeground(Color.black);
        devolucionesTxt.putClientProperty("FlatLaf.styleClass", "large");
        devolucionesTxt.setForeground(Color.black);
        registroTxt.putClientProperty("FlatLaf.styleClass", "large");
        registroTxt.setForeground(Color.black);
        edicionTxt.putClientProperty("FlatLaf.styleClass", "large");
        edicionTxt.setForeground(Color.black);
        reportesTxt.putClientProperty("FlatLaf.styleClass", "large");
        reportesTxt.setForeground(Color.black);
        seccionTxt.putClientProperty("FlatLaf.styleClass", "large");
        seccionTxt.setForeground(Color.black);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalPanel = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        nav1Txt = new javax.swing.JLabel();
        nav2Txt = new javax.swing.JLabel();
        toolTxt = new javax.swing.JLabel();
        inventarioTxt = new javax.swing.JLabel();
        ventasTxt = new javax.swing.JLabel();
        devolucionesTxt = new javax.swing.JLabel();
        registroTxt = new javax.swing.JLabel();
        edicionTxt = new javax.swing.JLabel();
        reportesTxt = new javax.swing.JLabel();
        seccionTxt = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(744, 419));

        principalPanel.setBackground(new java.awt.Color(255, 255, 255));

        Titulo.setText("Bienvenido");

        nav1Txt.setText("Sistema de Gestion para Tienda de Ropa Deportiva. Control y administracion optima y eficiente de inventario, ventas");

        nav2Txt.setText("y devoluciones.");

        toolTxt.setText("Esta herramienta permitira llevar un control completo y detallado de mavac, con acceso a funciones especificas como:");

        inventarioTxt.setText("Inventario");

        ventasTxt.setText("Ventas");

        devolucionesTxt.setText("Devoluciones");

        registroTxt.setText("Registro de Clientes y Compras");

        edicionTxt.setText("Edicion de Productos y Marcas");

        reportesTxt.setText("Reportes de Ventas y Existencias");

        seccionTxt.setText("Seccion de Promociones y Ofertas");

        javax.swing.GroupLayout principalPanelLayout = new javax.swing.GroupLayout(principalPanel);
        principalPanel.setLayout(principalPanelLayout);
        principalPanelLayout.setHorizontalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo)
                    .addComponent(nav1Txt)
                    .addComponent(nav2Txt)
                    .addComponent(toolTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inventarioTxt)
                    .addComponent(ventasTxt)
                    .addComponent(devolucionesTxt)
                    .addComponent(registroTxt)
                    .addComponent(edicionTxt)
                    .addComponent(reportesTxt)
                    .addComponent(seccionTxt)))
        );
        principalPanelLayout.setVerticalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addComponent(nav1Txt)
                .addGap(6, 6, 6)
                .addComponent(nav2Txt)
                .addGap(41, 41, 41)
                .addComponent(toolTxt)
                .addGap(12, 12, 12)
                .addComponent(inventarioTxt)
                .addGap(6, 6, 6)
                .addComponent(ventasTxt)
                .addGap(6, 6, 6)
                .addComponent(devolucionesTxt)
                .addGap(6, 6, 6)
                .addComponent(registroTxt)
                .addGap(6, 6, 6)
                .addComponent(edicionTxt)
                .addGap(6, 6, 6)
                .addComponent(reportesTxt)
                .addGap(6, 6, 6)
                .addComponent(seccionTxt))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel devolucionesTxt;
    private javax.swing.JLabel edicionTxt;
    private javax.swing.JLabel inventarioTxt;
    private javax.swing.JLabel nav1Txt;
    private javax.swing.JLabel nav2Txt;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JLabel registroTxt;
    private javax.swing.JLabel reportesTxt;
    private javax.swing.JLabel seccionTxt;
    private javax.swing.JLabel toolTxt;
    private javax.swing.JLabel ventasTxt;
    // End of variables declaration//GEN-END:variables
}
